apiVersion: apps/v1
kind: Deployment
metadata:
  name: <PROJECT ID>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <PROJECT ID>
  template:
    metadata:
      labels:
        app: <PROJECT ID>
    spec:
      containers:
      - name: <PROJECT ID>
        image: gcr.io/<PROJECT ID>/gcb-docker-compose:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
